name: tests
on:
  push:
  pull_request:

jobs:
  tests_on_intel_macos:
    name: Tests on macOS (x86_64)
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: x86_64 tests on macOS
      run: |
        ./.ci/run-cmake-test.sh x86_64-darwin
    - name: Collect artifacts
      run: |
        mkdir -p releases
        mv *     releases/
        chmod -R +x releases/
        tar -cvf all-artifacts.tar.bz2 releases/
    - name: Publish collected artifacts
      uses: actions/upload-artifact@v4
      with:
        name: all-artifacts
        path: all-artifacts.tar.bz2
        ./.ci/run-cmake-test.sh x86_64-mingw32 -DCMAKE_TOOLCHAIN_FILE=../cmake/x86_64-w64-mingw32.cmake
    - name: x86 tests on Wine
      run: |
        ./.ci/run-cmake-test.sh i686-mingw32 -DCMAKE_TOOLCHAIN_FILE=../cmake/i686-w64-mingw32.cmake
